import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#acabaa",
        "tertiary-fixed": "#5e5e5e",
        "outline-variant": "#c6c6c6",
        "primary-container": "#3b3b3b",
        "inverse-primary": "#c6c6c6",
        "surface-container-low": "#f6f3ec",
        "on-tertiary-container": "#ffffff",
        "surface-bright": "#fcf9f2",
        "secondary-container": "#d6d4d3",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#747474",
        "primary-fixed-dim": "#474747",
        "on-background": "#1c1c18",
        "on-secondary-fixed-variant": "#3b3b3b",
        "surface-dim": "#dcdad3",
        "secondary-fixed": "#c8c6c6",
        "surface-container-highest": "#e5e2db",
        secondary: "#5f5e5e",
        "inverse-surface": "#31312c",
        "on-primary-fixed-variant": "#e2e2e2",
        error: "#ba1a1a",
        "surface-tint": "#5e5e5e",
        tertiary: "#3b3b3b",
        "on-tertiary-fixed": "#ffffff",
        "on-error-container": "#410002",
        "primary-fixed": "#5e5e5e",
        "on-error": "#ffffff",
        "surface-container": "#f1eee7",
        "on-surface": "#1c1c18",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-container": "#ffffff",
        surface: "#fcf9f2",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-container": "#1b1c1c",
        "surface-container-high": "#ebe8e1",
        "tertiary-fixed-dim": "#474747",
        background: "#fcf9f2",
        outline: "#777777",
        "on-primary": "#e2e2e2",
        "on-surface-variant": "#474747",
        "on-tertiary": "#e2e2e2",
        "on-tertiary-fixed-variant": "#e2e2e2",
        "inverse-on-surface": "#f3f0e9",
        "surface-variant": "#e5e2db",
        primary: "#000000",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Work Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        full: "9999px",
      },
      letterSpacing: {
        tightest: "-0.04em",
        tighter: "-0.02em",
      },
    },
  },
  plugins: [],
};

export default config;
